let selectedArtist='All',shown=12;
const list=document.getElementById('tracks'),search=document.getElementById('search'),more=document.getElementById('more');
const escapeHTML=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function trackCard(t,i){
 const cover=artwork[t.id];
 const link=(url,label)=>`<a href="${escapeHTML(url)}" ${['YouTube','SoundCloud'].includes(label)?`data-play="${t.id}" data-source="${label.toLowerCase()}"`:'target="_blank" rel="noopener"'} aria-label="${escapeHTML(t.title)} on ${label}">${label.toUpperCase()}</a>`;
 return `<article class="track" data-track="${t.id}"><div class="track-name"><span class="track-number">${String(i+1).padStart(2,'0')}</span><button class="art-play" data-play="${t.id}" aria-label="Play ${escapeHTML(t.title)}"><img src="${cover.artwork}" alt="${cover.missing?'Cover not on file':`Artwork for ${escapeHTML(t.title)}`}" loading="lazy" width="80" height="80"><span aria-hidden="true">▶</span></button><div><h4>${escapeHTML(t.title)}</h4><p>${escapeHTML(t.credit||t.artist)}</p><div class="copy-badge">${t.audio?'ARCHIVE COPY':'PLATFORM EMBED'}</div></div></div><span class="track-type">${escapeHTML(t.type)}</span><div class="track-links"><span class="duration">${t.duration||''}</span><button class="track-play" data-play="${t.id}" aria-label="Listen to ${escapeHTML(t.title)}">PLAY</button>${t.spotify?link(`https://open.spotify.com/${t.spotifyKind==='album'?'album':'track'}/${t.spotify}`,'Spotify'):''}${t.youtube?link(`https://music.youtube.com/watch?v=${t.youtube}`,'YouTube'):''}${t.soundcloud?link(t.soundcloud,'SoundCloud'):''}${t.audio?`<a href="${t.audio}" download="${escapeHTML(t.originalFilename||t.title+'.mp3')}">DOWNLOAD</a>`:''}</div></article>`;
}
function render(){const query=search.value.trim().toLocaleLowerCase();const found=catalog.filter(t=>(selectedArtist==='All'||t.artist===selectedArtist)&&(t.title+' '+t.artist+' '+(t.credit||'')).toLocaleLowerCase().includes(query));list.innerHTML=found.slice(0,shown).map(trackCard).join('');more.hidden=shown>=found.length;document.getElementById('results-status').textContent=found.length?`Showing ${Math.min(shown,found.length)} of ${found.length} tracks`:'No tracks found. Try another title or artist.';}
function chooseFilter(artist){selectedArtist=artist;shown=12;document.querySelectorAll('[data-filter]').forEach(b=>{const active=b.dataset.filter===artist;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});render();}
document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>chooseFilter(button.dataset.filter)));
search.addEventListener('input',()=>{shown=12;render();});
more.addEventListener('click',()=>{const count=list.children.length;shown+=12;render();const row=list.children[count];row?.querySelector('button')?.focus({preventScroll:true});row?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'center'});});
document.getElementById('fetch-archive')?.addEventListener('click',()=>{search.value='';chooseFilter('Fetch Quest');});
document.getElementById('total-count').textContent=`${catalog.length} TRACKS / THE ARCHIVE`;document.getElementById('year').textContent=new Date().getFullYear();
const viewControls=document.createElement('div');viewControls.className='catalog-views';viewControls.setAttribute('role','group');viewControls.setAttribute('aria-label','Catalog display');viewControls.innerHTML='<button data-view="artwork" class="active" aria-pressed="true">ARTWORK</button><button data-view="list" aria-pressed="false">TRACK LIST</button>';document.querySelector('.archive-heading').after(viewControls);list.classList.add('artwork-grid');document.querySelector('.list-header').hidden=true;
viewControls.addEventListener('click',event=>{const button=event.target.closest('[data-view]');if(!button)return;const grid=button.dataset.view==='artwork';list.classList.toggle('artwork-grid',grid);document.querySelector('.list-header').hidden=grid;viewControls.querySelectorAll('button').forEach(b=>{const active=b===button;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});});
render();
