const catalog = [
  {
    "title": "Waverider",
    "id": "WrjCeMjexWc",
    "duration": "3:14",
    "artist": "Fetch Quest",
    "type": "Release",
    "credit": null,
    "spotify": "0DXO8YcURVZYbte55K0kwI",
    "youtube": "WrjCeMjexWc",
    "soundcloud": "https://soundcloud.com/fetchquest/waverider",
    "soundcloudId": 768167185,
    "releaseDate": "2020-02-28",
    "audio": "assets/audio/1rxBwwts7B2R8tWpnunV1HZhdZfPUePM_.mp3",
    "drive": "https://drive.google.com/file/d/1rxBwwts7B2R8tWpnunV1HZhdZfPUePM_/view?usp=drivesdk",
    "originalFilename": "Fetch Quest - Waverider_Mastered.mp3",
    "audioBytes": 7743808
  },
  {
    "title": "Hotwire",
    "id": "0jZfu7AWHM0",
    "duration": "3:34",
    "artist": "Fetch Quest",
    "type": "Release",
    "credit": null,
    "spotify": "2sJNzaaelWiQBhxULA4DPO",
    "youtube": "0jZfu7AWHM0"
  },
  {
    "title": "Concentrated Madness",
    "id": "3yLBYcHJ2VY",
    "duration": "4:21",
    "artist": "Fetch Quest",
    "type": "Release",
    "credit": null,
    "spotify": "0c1S2sFCGTHT63Mmt4WkSx",
    "youtube": "3yLBYcHJ2VY",
    "soundcloud": "https://soundcloud.com/fetchquest/fetch-quest-concentrated-madness",
    "soundcloudId": 853237624,
    "releaseDate": "2020-07-06",
    "audio": "assets/audio/10R598uT3w4Iz9hNRdLg9GeTHEYPcKrOB.mp3",
    "drive": "https://drive.google.com/file/d/10R598uT3w4Iz9hNRdLg9GeTHEYPcKrOB/view?usp=drivesdk",
    "originalFilename": "Fetch Quest - Concentrated Madness_Mastered.mp3",
    "audioBytes": 10412478
  },
  {
    "title": "Guesswork",
    "id": "IDB6aJWg4lg",
    "duration": "3:36",
    "artist": "Fetch Quest",
    "type": "Release",
    "credit": null,
    "spotify": "1Nbf5DvMU1xk51bEazSVVW",
    "youtube": "IDB6aJWg4lg",
    "soundcloud": "https://soundcloud.com/fetchquest/guesswork",
    "soundcloudId": 596056938,
    "releaseDate": "2019-03-26",
    "audio": "assets/audio/1Vvrzml_z_ajhz7DZ474lthCMf5p9QYxV.mp3",
    "drive": "https://drive.google.com/file/d/1Vvrzml_z_ajhz7DZ474lthCMf5p9QYxV/view?usp=drivesdk",
    "originalFilename": "Guesswork_Bass House 10_Mastered.mp3",
    "audioBytes": 8614216,
    "audioNote": "320 kbps listening copy made from the WAV master. The unmodified WAV is preserved in the original masters backup."
  },
  {
    "title": "Vernyi",
    "id": "dG6aKvJk3sM",
    "duration": "4:21",
    "artist": "Fetch Quest",
    "type": "Release",
    "credit": null,
    "spotify": "2wYSq6zpv2SKQsYevyVcsn",
    "youtube": "dG6aKvJk3sM",
    "audio": "assets/audio/1IMs9FXrFzrL2ZCcvLcjmgfXRKvwZViOy.mp3",
    "drive": "https://drive.google.com/file/d/1IMs9FXrFzrL2ZCcvLcjmgfXRKvwZViOy/view?usp=drivesdk",
    "originalFilename": "Fetch Quest - Vernyi_Mastered.mp3",
    "audioBytes": 10426061
  },
  {
    "title": "Speedrun",
    "id": "d7FTtwyaIcI",
    "duration": "3:39",
    "artist": "Fetch Quest",
    "type": "Release",
    "credit": null,
    "spotify": "1wqZVMQ1dQfcktU46SXzFy",
    "youtube": "d7FTtwyaIcI",
    "soundcloud": "https://soundcloud.com/fetchquest/speedrun",
    "soundcloudId": 1149438004,
    "releaseDate": "2021-10-28",
    "audio": "assets/audio/1WzZFax8dq3MkmSioaY1j_vOKAlOlaxJX.mp3",
    "drive": "https://drive.google.com/file/d/1WzZFax8dq3MkmSioaY1j_vOKAlOlaxJX/view?usp=drivesdk",
    "originalFilename": "Fetch Quest - SpeedRun_Mastered.mp3",
    "audioBytes": 8744821
  },
  {
    "title": "Zoology",
    "id": "FPeV7PODP1s",
    "duration": "4:47",
    "artist": "Fetch Quest",
    "type": "Release",
    "credit": null,
    "youtube": "FPeV7PODP1s",
    "soundcloud": "https://soundcloud.com/fetchquest/zoology",
    "soundcloudId": 345493956,
    "releaseDate": "2017-10-05",
    "audio": "assets/audio/1luP0dlNDMDc9dDYEp6QVDZg7ocMdxe7e.mp3",
    "drive": "https://drive.google.com/file/d/1luP0dlNDMDc9dDYEp6QVDZg7ocMdxe7e/view?usp=drivesdk",
    "originalFilename": "Zoology_mastered.mp3",
    "audioBytes": 11477229
  },
  {
    "title": "Flesh",
    "id": "ATNTVVZCWkU",
    "duration": "3:57",
    "artist": "Fetch Quest",
    "type": "Release",
    "credit": null,
    "spotify": "5f6GQPC488w6wzycnY7lpo",
    "youtube": "ATNTVVZCWkU",
    "soundcloud": "https://soundcloud.com/fetchquest/flesh",
    "soundcloudId": 938621467,
    "releaseDate": "2020-11-30",
    "audio": "assets/audio/13zcnVLAT8_zfe7RYHU-JUWt8EsZ7irXX.mp3",
    "drive": "https://drive.google.com/file/d/13zcnVLAT8_zfe7RYHU-JUWt8EsZ7irXX/view?usp=drivesdk",
    "originalFilename": "Fetch Quest - Flesh.mp3",
    "audioBytes": 9468935
  },
  {
    "title": "Zircon",
    "id": "X5Rpm8JVQBg",
    "duration": "4:56",
    "artist": "Fetch Quest",
    "type": "Release",
    "credit": null,
    "spotify": "1XqhwzdZIB6ahY1u07ZtFk",
    "youtube": "X5Rpm8JVQBg",
    "soundcloud": "https://soundcloud.com/fetchquest/zircon",
    "soundcloudId": 555284271,
    "releaseDate": "2019-01-07"
  },
  {
    "title": "Framework",
    "id": "ZCJ1nJ3Q79E",
    "duration": "5:16",
    "artist": "Fetch Quest",
    "type": "Release",
    "credit": null,
    "youtube": "ZCJ1nJ3Q79E"
  },
  {
    "title": "Touchstone",
    "id": "hL2ZWAv0278",
    "duration": "4:07",
    "artist": "Fetch Quest",
    "type": "Release",
    "credit": null,
    "youtube": "hL2ZWAv0278",
    "soundcloud": "https://soundcloud.com/fetchquest/touchstone",
    "soundcloudId": 335548866,
    "releaseDate": "2017-07-30"
  },
  {
    "title": "Dog’s Dogma",
    "id": "3wdB6cA1KX4",
    "duration": "3:51",
    "artist": "Fetch Quest",
    "type": "Release",
    "credit": null,
    "spotify": "1XUNDs23cW4UI6C1OPZSft",
    "youtube": "3wdB6cA1KX4",
    "audio": "assets/audio/1cpz3FTZkRqJycxs7AnvxOc6ackZqUMfk.mp3",
    "drive": "https://drive.google.com/file/d/1cpz3FTZkRqJycxs7AnvxOc6ackZqUMfk/view?usp=drivesdk",
    "originalFilename": "Fetch Quest - Dog's Dogma.mp3",
    "audioBytes": 9226519
  },
  {
    "title": "Pseudoscience",
    "id": "BstitX2x7vM",
    "duration": "6:03",
    "artist": "Fetch Quest",
    "type": "Release",
    "credit": null,
    "spotify": "4PjDcRrjThtPVomTW4P6ek",
    "youtube": "BstitX2x7vM",
    "soundcloud": "https://soundcloud.com/fetchquest/pseudoscience",
    "soundcloudId": 550743192,
    "releaseDate": "2018-12-27",
    "audio": "assets/audio/1SuGyvk7Qm_oKYxHhPyZ4S49fRfLCfSF4.mp3",
    "drive": "https://drive.google.com/file/d/1SuGyvk7Qm_oKYxHhPyZ4S49fRfLCfSF4/view?usp=drivesdk",
    "originalFilename": "Pseudoscience_Mastered.mp3",
    "audioBytes": 14482355
  },
  {
    "title": "Omnipotence",
    "id": "KRCBjxM92Uk",
    "duration": "3:38",
    "artist": "Fetch Quest",
    "type": "Release",
    "credit": null,
    "youtube": "KRCBjxM92Uk",
    "soundcloud": "https://soundcloud.com/fetchquest/omnipotence",
    "soundcloudId": 717532303,
    "releaseDate": "2019-11-23",
    "audio": "assets/audio/1fqzUS4AEY8ukTSiCC6uhrmZmJTYEddD9.mp3",
    "drive": "https://drive.google.com/file/d/1fqzUS4AEY8ukTSiCC6uhrmZmJTYEddD9/view?usp=drivesdk",
    "originalFilename": "Fetch Quest - Omnipotence_Mastered.mp3",
    "audioBytes": 8705114
  },
  {
    "title": "Angry Teenagers",
    "id": "f0JpJon_YqM",
    "duration": "3:48",
    "artist": "Fetch Quest",
    "type": "Release",
    "credit": null,
    "spotify": "0nRVlYqSikAT7XlELocwEn",
    "youtube": "f0JpJon_YqM",
    "audio": "assets/audio/1ECdYg9Nkm8F_cR6G-q-q5sQJ2Dc9-5XA.mp3",
    "drive": "https://drive.google.com/file/d/1ECdYg9Nkm8F_cR6G-q-q5sQJ2Dc9-5XA/view?usp=drivesdk",
    "originalFilename": "Fetch Quest - Angry Teenagers.mp3",
    "audioBytes": 9104266
  },
  {
    "title": "Nanowire",
    "id": "5OS3_Y8_raw",
    "duration": "4:10",
    "artist": "Fetch Quest",
    "type": "Release",
    "credit": null,
    "spotify": "6MUmAIq7I603kHWlb7cYSz",
    "youtube": "5OS3_Y8_raw"
  },
  {
    "title": "Kinship",
    "id": "JpVo3seANv0",
    "duration": "2:56",
    "artist": "Fetch Quest",
    "type": "Release",
    "credit": null,
    "spotify": "5SpiIyEcPyajfs1kPQ8qce",
    "youtube": "JpVo3seANv0",
    "audio": "assets/audio/1LV0MeSyB4RKbEIPOe3XY6vIov0NyW0QP.mp3",
    "drive": "https://drive.google.com/file/d/1LV0MeSyB4RKbEIPOe3XY6vIov0NyW0QP/view?usp=drivesdk",
    "originalFilename": "Fetch Quest - Kinship.mp3",
    "audioBytes": 7027008
  },
  {
    "title": "Disco Mbobulate",
    "id": "XP1oxENYnQ4",
    "duration": "4:23",
    "artist": "Fetch Quest",
    "type": "Release",
    "credit": null,
    "spotify": "0Yg5C3y4fZ1E7d7GbxAgVq",
    "youtube": "XP1oxENYnQ4",
    "audio": "assets/audio/1n8oH5mWffB2W6VkkAujS3cPSEiErPslL.mp3",
    "drive": "https://drive.google.com/file/d/1n8oH5mWffB2W6VkkAujS3cPSEiErPslL/view?usp=drivesdk",
    "originalFilename": "Fetch Quest - Disco Mbobulate.mp3",
    "audioBytes": 10502339
  },
  {
    "title": "Trapwire",
    "id": "s4lCTG9Pzq4",
    "duration": "3:18",
    "artist": "Fetch Quest",
    "type": "Release",
    "credit": null,
    "spotify": "6oazKy3qGZImKZWp8SEKyf",
    "youtube": "s4lCTG9Pzq4"
  },
  {
    "title": "Ascendant Decade",
    "id": "Remok-ADVHM",
    "duration": "5:45",
    "artist": "Fetch Quest",
    "type": "Release",
    "credit": null,
    "youtube": "Remok-ADVHM",
    "soundcloud": "https://soundcloud.com/fetchquest/ascendant-decade",
    "soundcloudId": 773150266,
    "releaseDate": "2020-03-09",
    "audio": "assets/audio/1BbKcctxJKvDMP4UdmMTeh9rEhl7gw240.mp3",
    "drive": "https://drive.google.com/file/d/1BbKcctxJKvDMP4UdmMTeh9rEhl7gw240/view?usp=drivesdk",
    "originalFilename": "Fetch Quest - Ascendant Decade_Mastered.mp3",
    "audioBytes": 13778094
  },
  {
    "title": "Glazed Curd",
    "id": "V0oW0gPL5vo",
    "duration": "3:47",
    "artist": "Fetch Quest",
    "type": "Release",
    "credit": null,
    "spotify": "157cUaqPeIFLb6h8Lu2Dor",
    "youtube": "V0oW0gPL5vo",
    "soundcloud": "https://soundcloud.com/fetchquest/glazed-curd",
    "soundcloudId": 1020955054,
    "releaseDate": "2021-04-02",
    "audio": "assets/audio/1BkWdPxkScQ0pEaIH7JlgNRS3_8WK-pS9.mp3",
    "drive": "https://drive.google.com/file/d/1BkWdPxkScQ0pEaIH7JlgNRS3_8WK-pS9/view?usp=drivesdk",
    "originalFilename": "Fetch Quest - Glazed Curd_Mastered.mp3",
    "audioBytes": 9044706
  },
  {
    "title": "Bones",
    "id": "6UAUJfoGDfI",
    "duration": "5:51",
    "artist": "Fetch Quest",
    "type": "Release",
    "credit": null,
    "spotify": "3TVG0C7iy3Pfg9t3ibD578",
    "youtube": "6UAUJfoGDfI",
    "audio": "assets/audio/17z6KRmOQrbcfmkhWgUf3oB2jnM2_5r3K.mp3",
    "drive": "https://drive.google.com/file/d/17z6KRmOQrbcfmkhWgUf3oB2jnM2_5r3K/view?usp=drivesdk",
    "originalFilename": "Bones.mp3",
    "audioBytes": 9462666
  },
  {
    "title": "Ian Oliver ft. Eastenders - Vino Vino_-_slowed w reverb",
    "id": "Ruk54SRuRJg",
    "duration": "",
    "artist": "peacepipe04",
    "type": "Remix / edit",
    "youtube": "Ruk54SRuRJg"
  },
  {
    "title": "generic indie pop song",
    "id": "oasfLfWYgTo",
    "duration": "",
    "artist": "peacepipe04",
    "type": "Channel archive",
    "youtube": "oasfLfWYgTo"
  },
  {
    "title": "the trashbird",
    "id": "Z6MmnzhYt7I",
    "duration": "",
    "artist": "peacepipe04",
    "type": "Channel archive",
    "youtube": "Z6MmnzhYt7I"
  },
  {
    "title": "Cupcakke - Duck Duck Goose but it’s disco INSTRUMENTAL",
    "id": "ZODS3DRGkhc",
    "duration": "",
    "artist": "peacepipe04",
    "type": "Remix / edit",
    "youtube": "ZODS3DRGkhc",
    "audio": "assets/audio/1lwZiPgcz-1PF-RVO4AzwHLEhjfJL3WUc.mp3",
    "drive": "https://drive.google.com/file/d/1lwZiPgcz-1PF-RVO4AzwHLEhjfJL3WUc/view?usp=drivesdk",
    "originalFilename": "Instrumental_Cupcakke - Duck Duck Goose peacepipe04 disco remix.mp3",
    "audioBytes": 6001949
  },
  {
    "title": "Cupcakke - Duck Duck Goose but it’s disco",
    "id": "4DikQvqlHYI",
    "duration": "",
    "artist": "peacepipe04",
    "type": "Remix / edit",
    "youtube": "4DikQvqlHYI",
    "audio": "assets/audio/11KmavVwV2B3bz45uOEUph4G-I_9sFcLU.mp3",
    "drive": "https://drive.google.com/file/d/11KmavVwV2B3bz45uOEUph4G-I_9sFcLU/view?usp=drivesdk",
    "originalFilename": "Cupcakke - Duck Duck Goose peacepipe04 disco remix.mp3",
    "audioBytes": 6195256
  },
  {
    "title": "Martin Garrix - Animals (peacepipe04 cheap cumbia remix)",
    "id": "h8mS3jgxp58",
    "duration": "",
    "artist": "peacepipe04",
    "type": "Remix / edit",
    "youtube": "h8mS3jgxp58",
    "audio": "assets/audio/18WlrYhLvsZqqFJcSAichEuj0AVXO5VjT.mp3",
    "drive": "https://drive.google.com/file/d/18WlrYhLvsZqqFJcSAichEuj0AVXO5VjT/view?usp=drivesdk",
    "originalFilename": "Animals remix.mp3",
    "audioBytes": 4889133
  },
  {
    "title": "Payload",
    "id": "cN5RchsIaLk",
    "duration": "",
    "artist": "Audionerds",
    "type": "Channel archive",
    "youtube": "cN5RchsIaLk",
    "audio": "assets/audio/1NMzkImRHV1mO67gOR9Q729tgtNZ2B_Sk.mp3",
    "drive": "https://drive.google.com/file/d/1NMzkImRHV1mO67gOR9Q729tgtNZ2B_Sk/view?usp=drivesdk",
    "originalFilename": "Audionerds - Payload (Original mix).mp3",
    "audioBytes": 13614045
  },
  {
    "title": "Phil Fuldner - Miami Pop (peacepipe04 remix)",
    "id": "k9DkmBd2SFg",
    "duration": "",
    "artist": "peacepipe04",
    "type": "Remix / edit",
    "youtube": "k9DkmBd2SFg",
    "audio": "assets/audio/1P8pH3wu4Bm5bOPX7bk9KzPz1jgfgrnzR.mp3",
    "drive": "https://drive.google.com/file/d/1P8pH3wu4Bm5bOPX7bk9KzPz1jgfgrnzR/view?usp=drivesdk",
    "originalFilename": "Phil Fuldner - Miami Pop (peacepipe04 remix).mp3",
    "audioBytes": 6078227
  },
  {
    "title": "um jogo no paraíso SPED UP",
    "id": "ZAHhsKEW2jk",
    "duration": "",
    "artist": "peacepipe04",
    "type": "Channel archive",
    "youtube": "ZAHhsKEW2jk",
    "audio": "assets/audio/1Ni6SDJkM4WDSafBrux8DBZm8nXw3NtLa.mp3",
    "drive": "https://drive.google.com/file/d/1Ni6SDJkM4WDSafBrux8DBZm8nXw3NtLa/view?usp=drivesdk",
    "originalFilename": "peacepipe04 - um jogo no paraiso_SPED UP.mp3",
    "audioBytes": 7239109
  },
  {
    "title": "um jogo no paraíso",
    "id": "zB1mfz7o_-0",
    "duration": "",
    "artist": "peacepipe04",
    "type": "Channel archive",
    "youtube": "zB1mfz7o_-0",
    "audio": "assets/audio/1SQRtHh-nH0mgMdWE0p8RFYmOHJ_NoQVZ.mp3",
    "drive": "https://drive.google.com/file/d/1SQRtHh-nH0mgMdWE0p8RFYmOHJ_NoQVZ/view?usp=drivesdk",
    "originalFilename": "peacepipe04 - um jogo no paraiso.mp3",
    "audioBytes": 8555680
  },
  {
    "title": "Cupcakke - CPR but it’s 70s corno music INSTRUMENTAL",
    "id": "GL55YP8_0E4",
    "duration": "",
    "artist": "peacepipe04",
    "type": "Remix / edit",
    "youtube": "GL55YP8_0E4",
    "audio": "assets/audio/1i-MH0v35eHFjeIHpJJiQ9Fyj1zUr5wjN.mp3",
    "drive": "https://drive.google.com/file/d/1i-MH0v35eHFjeIHpJJiQ9Fyj1zUr5wjN/view?usp=drivesdk",
    "originalFilename": "Cupcakke - CPR but its 70s corno music_INSTRUMENTAL.mp3",
    "audioBytes": 7488839
  },
  {
    "title": "Cupcakke - CPR but it’s 70s corno music",
    "id": "ngFdLogRMtg",
    "duration": "",
    "artist": "peacepipe04",
    "type": "Remix / edit",
    "youtube": "ngFdLogRMtg",
    "audio": "assets/audio/10i5S83Tww9JX4zEGZqTwNhMJi6wDJYOq.mp3",
    "drive": "https://drive.google.com/file/d/10i5S83Tww9JX4zEGZqTwNhMJi6wDJYOq/view?usp=drivesdk",
    "originalFilename": "Cupcakke - CPR but its 70s corno music.mp3",
    "audioBytes": 7488839
  },
  {
    "title": "naya - bubble town (peacepipe04 remix)",
    "id": "p8XDTN84aKs",
    "duration": "",
    "artist": "peacepipe04",
    "type": "Remix / edit",
    "youtube": "p8XDTN84aKs"
  },
  {
    "title": "The Surfaris - Wipe out (peacepipe04 remix)",
    "id": "T3e_CcZFl9w",
    "duration": "",
    "artist": "peacepipe04",
    "type": "Remix / edit",
    "youtube": "T3e_CcZFl9w",
    "audio": "assets/audio/15oyIgTutaewP4sC-Ipybq9-EX7BVbuE7.mp3",
    "drive": "https://drive.google.com/file/d/15oyIgTutaewP4sC-Ipybq9-EX7BVbuE7/view?usp=drivesdk",
    "originalFilename": "wipeout final pp04 remix.mp3",
    "audioBytes": 4451321
  },
  {
    "title": "UZI boomstick",
    "id": "G1nBOYhlirA",
    "duration": "",
    "artist": "peacepipe04",
    "type": "Channel archive",
    "youtube": "G1nBOYhlirA",
    "audio": "assets/audio/1okU0lcY0mQbmWU1wZLx8rRVU9SjZ6oFH.mp3",
    "drive": "https://drive.google.com/file/d/1okU0lcY0mQbmWU1wZLx8rRVU9SjZ6oFH/view?usp=drivesdk",
    "originalFilename": "peacepipe04 - UZI boomstick.mp3",
    "audioBytes": 7871272
  },
  {
    "title": "mad woman ting",
    "id": "VHzt6B4mPl4",
    "duration": "",
    "artist": "peacepipe04",
    "type": "Channel archive",
    "youtube": "VHzt6B4mPl4",
    "audio": "assets/audio/1skceFpjQ_E0n_Wx5t_NQVwZA5aUvkZhY.mp3",
    "drive": "https://drive.google.com/file/d/1skceFpjQ_E0n_Wx5t_NQVwZA5aUvkZhY/view?usp=drivesdk",
    "originalFilename": "peacepipe04 - mad woman ting [ffll].mp3",
    "audioBytes": 8981998
  },
  {
    "title": "a room of tools guided by marked knight",
    "id": "TXr-XnyhmzQ",
    "duration": "",
    "artist": "peacepipe04",
    "type": "Channel archive",
    "youtube": "TXr-XnyhmzQ",
    "audio": "assets/audio/1uVE_U4BtbIX4U3bPeKzZY4o0PXAs2xqN.mp3",
    "drive": "https://drive.google.com/file/d/1uVE_U4BtbIX4U3bPeKzZY4o0PXAs2xqN/view?usp=drivesdk",
    "originalFilename": "peacepipe04 - a room of tools guided by marked knight [ffll].mp3",
    "audioBytes": 8672709
  },
  {
    "title": "descendant decade",
    "id": "ju_Drex7dG8",
    "duration": "",
    "artist": "peacepipe04",
    "type": "Channel archive",
    "youtube": "ju_Drex7dG8",
    "audio": "assets/audio/1XS8rW6VENFUvNPyfcLinHP2QRd0rVDEY.mp3",
    "drive": "https://drive.google.com/file/d/1XS8rW6VENFUvNPyfcLinHP2QRd0rVDEY/view?usp=drivesdk",
    "originalFilename": "peacepipe04 - descendant decade [ffll].mp3",
    "audioBytes": 8078162
  },
  {
    "title": "ûëçåøßœîæ",
    "id": "xPmZbntLoDQ",
    "duration": "",
    "artist": "peacepipe04",
    "type": "Channel archive",
    "youtube": "xPmZbntLoDQ",
    "audio": "assets/audio/19THyla51bqK_EMltZZ1nQy2iRnfATPMu.mp3",
    "drive": "https://drive.google.com/file/d/19THyla51bqK_EMltZZ1nQy2iRnfATPMu/view?usp=drivesdk",
    "originalFilename": "peacepipe04 - ûëçåøßœîæ [ffll].mp3",
    "audioBytes": 4201590
  },
  {
    "title": "ainsley kensington",
    "id": "lOeJPbG_mtw",
    "duration": "",
    "artist": "peacepipe04",
    "type": "Channel archive",
    "youtube": "lOeJPbG_mtw",
    "audio": "assets/audio/1uyfUwfXk7CC15fL47rzKwOQuzdx-Xv0k.mp3",
    "drive": "https://drive.google.com/file/d/1uyfUwfXk7CC15fL47rzKwOQuzdx-Xv0k/view?usp=drivesdk",
    "originalFilename": "peacepipe04 - ainsley kensington [ffll].mp3",
    "audioBytes": 8207729
  },
  {
    "title": "Eliminate - Walk Away (fetch quest remix)",
    "id": "geLKG9QxbeU",
    "duration": "",
    "artist": "Fetch Quest",
    "type": "Remix / edit",
    "youtube": "geLKG9QxbeU",
    "soundcloud": "https://soundcloud.com/fetchquest/eliminate-walk-away-fetch-quest-remix",
    "soundcloudId": 1278776899,
    "releaseDate": "2022-05-31",
    "audio": "assets/audio/1RLEEN6zarL0kVFI16ESl-xB3oj-nO6tx.mp3",
    "drive": "https://drive.google.com/file/d/1RLEEN6zarL0kVFI16ESl-xB3oj-nO6tx/view?usp=drivesdk",
    "originalFilename": "Eliminate - Walk Away (Fetch Quest Remix).mp3",
    "audioBytes": 8740641
  },
  {
    "title": "daft punk - technologic (audionerds remix)",
    "id": "XoOoF6o3_wY",
    "duration": "",
    "artist": "Audionerds",
    "type": "Remix / edit",
    "youtube": "XoOoF6o3_wY",
    "soundcloud": "https://soundcloud.com/fetchquest/daft-punk-technologic-audionerds-remix",
    "soundcloudId": 228429446,
    "releaseDate": "2015-10-14",
    "audio": "assets/audio/1wPtHHAI5SJeUeJSCIKWNMSRT30l8e3Ht.mp3",
    "drive": "https://drive.google.com/file/d/1wPtHHAI5SJeUeJSCIKWNMSRT30l8e3Ht/view?usp=drivesdk",
    "originalFilename": "Daft Punk - Technologic (Audionerds Remix).mp3",
    "audioBytes": 8852445
  },
  {
    "title": "crossover",
    "id": "_YEfQaKH8FU",
    "duration": "",
    "artist": "Fetch Quest",
    "type": "Channel archive",
    "youtube": "_YEfQaKH8FU",
    "soundcloud": "https://soundcloud.com/fetchquest/crossover",
    "soundcloudId": 291556091,
    "releaseDate": "2016-11-04"
  },
  {
    "title": "badlands",
    "id": "WLgIaGV4_3U",
    "duration": "",
    "artist": "Fetch Quest",
    "type": "Channel archive",
    "youtube": "WLgIaGV4_3U",
    "soundcloud": "https://soundcloud.com/fetchquest/badlands",
    "soundcloudId": 291373617,
    "releaseDate": "2016-11-03"
  },
  {
    "title": "the unalived mouse & the gang of wolves",
    "id": "AF9uT6lS8rI",
    "duration": "",
    "artist": "peacepipe04",
    "type": "Channel archive",
    "youtube": "AF9uT6lS8rI"
  },
  {
    "title": "maledict",
    "id": "nH3TaACFswM",
    "duration": "",
    "artist": "Fetch Quest",
    "type": "Channel archive",
    "youtube": "nH3TaACFswM",
    "soundcloud": "https://soundcloud.com/fetchquest/maledict",
    "soundcloudId": 296967983,
    "releaseDate": "2016-12-09"
  },
  {
    "title": "intruder",
    "id": "LU6P3C4BhUs",
    "duration": "",
    "artist": "Fetch Quest",
    "type": "Channel archive",
    "youtube": "LU6P3C4BhUs",
    "soundcloud": "https://soundcloud.com/fetchquest/intruder",
    "soundcloudId": 338608197,
    "releaseDate": "2017-08-19",
    "audio": "assets/audio/1EkqauHpyLz4rKh8p0g5YMWyYJNfoDoNt.mp3",
    "drive": "https://drive.google.com/file/d/1EkqauHpyLz4rKh8p0g5YMWyYJNfoDoNt/view?usp=drivesdk",
    "originalFilename": "INTRUDER FINAL MASTERED.mp3",
    "audioBytes": 13882584
  },
  {
    "title": "jaeger (1st version)",
    "id": "HFJkEa3rylQ",
    "duration": "",
    "artist": "Audionerds",
    "type": "Channel archive",
    "youtube": "HFJkEa3rylQ",
    "audio": "assets/audio/1HBcGQpYBeEasBJt9fnsCoiZLe5z2xGJi.mp3",
    "drive": "https://drive.google.com/file/d/1HBcGQpYBeEasBJt9fnsCoiZLe5z2xGJi/view?usp=drivesdk",
    "originalFilename": "Audionerds - Jaeger ver. 1_MASTERED.mp3",
    "audioBytes": 12226407
  },
  {
    "title": "atomic punch",
    "id": "3ouEy-bigYQ",
    "duration": "",
    "artist": "Fetch Quest",
    "type": "Channel archive",
    "youtube": "3ouEy-bigYQ",
    "soundcloud": "https://soundcloud.com/fetchquest/atomic-punch",
    "soundcloudId": 302823612,
    "releaseDate": "2017-01-15"
  },
  {
    "title": "hitchhiker",
    "id": "JOwroFzvAXA",
    "duration": "",
    "artist": "Fetch Quest",
    "type": "Channel archive",
    "youtube": "JOwroFzvAXA",
    "soundcloud": "https://soundcloud.com/fetchquest/hitchhiker",
    "soundcloudId": 318697607,
    "releaseDate": "2017-04-20"
  },
  {
    "title": "Soulja boy X piano fantasia - crank that song for Denise mashup",
    "id": "MkgNTNv5Bhw",
    "duration": "",
    "artist": "peacepipe04",
    "type": "Remix / edit",
    "youtube": "MkgNTNv5Bhw"
  },
  {
    "title": "SexyBack but it’s only Timbaland",
    "id": "KV1enCR_pSA",
    "duration": "",
    "artist": "peacepipe04",
    "type": "Remix / edit",
    "youtube": "KV1enCR_pSA"
  },
  {
    "title": "Loompaskettee & Bandlez - Riddim Track (peacepipe04 carnival color rawstyle ReR)",
    "id": "JEctLae7BG0",
    "duration": "",
    "artist": "peacepipe04",
    "type": "Remix / edit",
    "youtube": "JEctLae7BG0",
    "audio": "assets/audio/1kvWaGTc-_Lb0bbdUyAL84ako7oSD5Z7D.mp3",
    "drive": "https://drive.google.com/file/d/1kvWaGTc-_Lb0bbdUyAL84ako7oSD5Z7D/view?usp=drivesdk",
    "originalFilename": "Loompaskettee & Bandlez - Riddim Track (peacepipe04 carnival color rawstyle rer).mp3",
    "audioBytes": 5156627
  },
  {
    "title": "sigma boy 🗿 but it’s cheap orchestra",
    "id": "O0sTEAC7zsA",
    "duration": "",
    "artist": "peacepipe04",
    "type": "Remix / edit",
    "youtube": "O0sTEAC7zsA"
  },
  {
    "title": "epic cheesy toast - art of war (peacepipe04 art of peace recolor)",
    "id": "up0emSzVhuQ",
    "duration": "",
    "artist": "peacepipe04",
    "type": "Remix / edit",
    "youtube": "up0emSzVhuQ",
    "audio": "assets/audio/1AO44wwveT8qkLuMthGv34Yl1VM0Psii5.mp3",
    "drive": "https://drive.google.com/file/d/1AO44wwveT8qkLuMthGv34Yl1VM0Psii5/view?usp=drivesdk",
    "originalFilename": "epic cheesy toast - art of war (peacepipe04 art of peace recolor).mp3",
    "audioBytes": 6620529
  },
  {
    "title": "super cool pumping music in the car",
    "id": "7dySB-q3W1w",
    "duration": "",
    "artist": "peacepipe04",
    "type": "Channel archive",
    "youtube": "7dySB-q3W1w"
  },
  {
    "title": "unity",
    "id": "-jZKuY45FeQ",
    "duration": "",
    "artist": "Fetch Quest",
    "type": "Channel archive",
    "youtube": "-jZKuY45FeQ",
    "soundcloud": "https://soundcloud.com/fetchquest/unity",
    "soundcloudId": 432172938,
    "releaseDate": "2018-04-19"
  },
  {
    "title": "baccpacc",
    "id": "COEG8DylnGk",
    "duration": "",
    "artist": "peacepipe04",
    "type": "Channel archive",
    "youtube": "COEG8DylnGk",
    "audio": "assets/audio/1_k9OPWQCXHEKLnILJZVIF2G8Wi-CQs6d.mp3",
    "drive": "https://drive.google.com/file/d/1_k9OPWQCXHEKLnILJZVIF2G8Wi-CQs6d/view?usp=drivesdk",
    "originalFilename": "peacepipe04 - baccpacc.mp3",
    "audioBytes": 8986192
  },
  {
    "title": "taurine groove",
    "id": "HSOTOJjwgC8",
    "duration": "",
    "artist": "peacepipe04",
    "type": "Channel archive",
    "youtube": "HSOTOJjwgC8"
  },
  {
    "title": "spankox - to the club (fetch quest remix)🕺🏽",
    "id": "zzK_kqMhiaE",
    "duration": "",
    "artist": "Fetch Quest",
    "type": "Remix / edit",
    "youtube": "zzK_kqMhiaE",
    "soundcloud": "https://soundcloud.com/fetchquest/spankox-to-the-club-fetch-quest-remix",
    "soundcloudId": 1534205821,
    "releaseDate": "2023-06-08",
    "audio": "assets/audio/1L5YW86ik2DwTk7XI90amAw0ULc7NtK8w.mp3",
    "drive": "https://drive.google.com/file/d/1L5YW86ik2DwTk7XI90amAw0ULc7NtK8w/view?usp=drivesdk",
    "originalFilename": "Spankox - To The Club (Fetch Quest Remix).mp3",
    "audioBytes": 10279776
  },
  {
    "title": "i like trains 🚂 [ambient]",
    "id": "GW5OeSKUGGE",
    "duration": "",
    "artist": "peacepipe04",
    "type": "Channel archive",
    "youtube": "GW5OeSKUGGE"
  },
  {
    "title": "lepidoptera 🦋",
    "id": "Gm4EFFE6PFM",
    "duration": "",
    "artist": "peacepipe04",
    "type": "Channel archive",
    "youtube": "Gm4EFFE6PFM"
  },
  {
    "title": "sport 🏀🥊",
    "id": "sf4qEpelhqQ",
    "duration": "",
    "artist": "peacepipe04",
    "type": "Channel archive",
    "youtube": "sf4qEpelhqQ"
  },
  {
    "id": "sc-218046485",
    "title": "Horizon",
    "artist": "Audionerds",
    "type": "SoundCloud archive",
    "duration": "6:02",
    "soundcloud": "https://soundcloud.com/fetchquest/horizon-out-now",
    "soundcloudId": 218046485,
    "releaseDate": "2015-08-06"
  },
  {
    "id": "sc-211693501",
    "title": "Crimson",
    "artist": "Audionerds",
    "type": "SoundCloud archive",
    "duration": "3:48",
    "soundcloud": "https://soundcloud.com/fetchquest/crimson-out-now",
    "soundcloudId": 211693501,
    "releaseDate": "2015-06-23"
  },
  {
    "id": "sc-191959883",
    "title": "Back",
    "artist": "Audionerds",
    "type": "SoundCloud archive",
    "duration": "4:56",
    "soundcloud": "https://soundcloud.com/fetchquest/back-original-mix-1",
    "soundcloudId": 191959883,
    "releaseDate": "2015-02-19",
    "audio": "assets/audio/1jpPghjKjV_cZ6aH2eHNoPUOYbtpildcl.mp3",
    "drive": "https://drive.google.com/file/d/1jpPghjKjV_cZ6aH2eHNoPUOYbtpildcl/view?usp=drivesdk",
    "originalFilename": "Audionerds - Back (Original Mix).mp3",
    "audioBytes": 11852347
  },
  {
    "id": "sc-181225059",
    "title": "Rush",
    "artist": "Audionerds",
    "type": "SoundCloud archive",
    "duration": "4:17",
    "soundcloud": "https://soundcloud.com/fetchquest/rush-original-mix",
    "soundcloudId": 181225059,
    "releaseDate": "2014-12-12"
  },
  {
    "id": "sc-166192778",
    "title": "Cerberus",
    "artist": "Audionerds",
    "type": "SoundCloud archive",
    "duration": "4:58",
    "soundcloud": "https://soundcloud.com/fetchquest/cerberus-original-mix",
    "soundcloudId": 166192778,
    "releaseDate": "2014-09-04"
  },
  {
    "id": "sc-162264310",
    "title": "Wanderlust",
    "artist": "Audionerds",
    "type": "SoundCloud archive",
    "duration": "3:53",
    "soundcloud": "https://soundcloud.com/fetchquest/wanderlust-original-mix",
    "soundcloudId": 162264310,
    "releaseDate": "2014-08-08"
  },
  {
    "id": "sc-161938426",
    "title": "Ramble",
    "artist": "Audionerds",
    "type": "SoundCloud archive",
    "duration": "4:33",
    "soundcloud": "https://soundcloud.com/fetchquest/ramble-original-mix",
    "soundcloudId": 161938426,
    "releaseDate": "2014-08-06",
    "audio": "assets/audio/1kYgx-AbHJsu5944G5khXfE12wPKlaiKU.mp3",
    "drive": "https://drive.google.com/file/d/1kYgx-AbHJsu5944G5khXfE12wPKlaiKU/view?usp=drivesdk",
    "originalFilename": "RAMBLE.mp3",
    "audioBytes": 10952690
  },
  {
    "id": "sc-159426983",
    "title": "Sander van Doorn, Martin Garrix, DVBBS ft. Aleesia - Gold Skies (Audionerds Remix)",
    "artist": "Audionerds",
    "type": "SoundCloud archive",
    "duration": "5:16",
    "soundcloud": "https://soundcloud.com/fetchquest/sander-van-doorn-martin-garrix-dvbbs-ft-aleesia-gold-skies-audionerds-remix",
    "soundcloudId": 159426983,
    "releaseDate": "2014-07-19"
  },
  {
    "id": "sc-157018699",
    "title": "Cowboy",
    "artist": "Epic Cheesy Toast",
    "type": "SoundCloud archive",
    "duration": "5:54",
    "soundcloud": "https://soundcloud.com/fetchquest/cowboy-original-mix",
    "soundcloudId": 157018699,
    "releaseDate": "2014-07-02"
  },
  {
    "id": "sc-151646095",
    "title": "Cataclysm (Preview)",
    "artist": "Epic Cheesy Toast",
    "type": "SoundCloud archive",
    "duration": "0:49",
    "soundcloud": "https://soundcloud.com/fetchquest/cataclysm-preview-1",
    "soundcloudId": 151646095,
    "releaseDate": "2014-05-28"
  },
  {
    "id": "sc-148327923",
    "title": "#NERD",
    "artist": "Epic Cheesy Toast",
    "type": "SoundCloud archive",
    "duration": "4:50",
    "soundcloud": "https://soundcloud.com/fetchquest/nerd-original-mix",
    "soundcloudId": 148327923,
    "releaseDate": "2014-05-07"
  },
  {
    "id": "sc-143482171",
    "title": "Popeska feat. Denny White - Heart Of Glass (Audionerds Remix)",
    "artist": "Epic Cheesy Toast",
    "type": "SoundCloud archive",
    "duration": "4:48",
    "soundcloud": "https://soundcloud.com/fetchquest/popeska-feat-denny-white-heart",
    "soundcloudId": 143482171,
    "releaseDate": "2014-04-07"
  },
  {
    "id": "sc-141846543",
    "title": "Havoc",
    "artist": "Epic Cheesy Toast",
    "type": "SoundCloud archive",
    "duration": "4:06",
    "soundcloud": "https://soundcloud.com/fetchquest/havoc-original-mix",
    "soundcloudId": 141846543,
    "releaseDate": "2014-03-28"
  },
  {
    "id": "sc-123517237",
    "title": "PRMT [Preview]",
    "artist": "Epic Cheesy Toast",
    "type": "SoundCloud archive",
    "duration": "2:15",
    "soundcloud": "https://soundcloud.com/fetchquest/prmt-preview",
    "soundcloudId": 123517237,
    "releaseDate": "2013-12-06"
  },
  {
    "id": "sc-123516494",
    "title": "Framework",
    "artist": "Epic Cheesy Toast",
    "type": "SoundCloud archive",
    "duration": "5:15",
    "soundcloud": "https://soundcloud.com/fetchquest/framework-original-mix-1",
    "soundcloudId": 123516494,
    "releaseDate": "2013-12-06",
    "youtube": "eM5e2KXR2d8"
  },
  {
    "id": "sc-118080584",
    "title": "Kids",
    "artist": "Epic Cheesy Toast",
    "type": "SoundCloud archive",
    "duration": "4:03",
    "soundcloud": "https://soundcloud.com/fetchquest/kids-original-mix",
    "soundcloudId": 118080584,
    "releaseDate": "2013-11-01"
  },
  {
    "id": "sc-113620964",
    "title": "The Origin Of Life",
    "artist": "Epic Cheesy Toast",
    "type": "SoundCloud archive",
    "duration": "5:22",
    "soundcloud": "https://soundcloud.com/fetchquest/the-origin-of-life",
    "soundcloudId": 113620964,
    "releaseDate": "2013-10-03"
  },
  {
    "id": "sc-105887583",
    "title": "Bonecrusher",
    "artist": "Epic Cheesy Toast",
    "type": "SoundCloud archive",
    "duration": "4:52",
    "soundcloud": "https://soundcloud.com/fetchquest/bonecrusher",
    "soundcloudId": 105887583,
    "releaseDate": "2013-08-17",
    "audio": "assets/audio/0B6qg46ChnRO7eGV1UUFXMDVydk0.mp3",
    "drive": "https://drive.google.com/file/d/0B6qg46ChnRO7eGV1UUFXMDVydk0/view?usp=drivesdk&resourcekey=0-91mW5dj-LeerO3uVIBJ1rQ",
    "originalFilename": "Bonecrusher.mp3",
    "audioBytes": 11701882
  },
  {
    "id": "sc-78908151",
    "title": "Space-Time Continuum",
    "artist": "Epic Cheesy Toast",
    "type": "SoundCloud archive",
    "duration": "5:16",
    "soundcloud": "https://soundcloud.com/fetchquest/epic-cheesy-toast-space-time",
    "soundcloudId": 78908151,
    "releaseDate": "2013-02-12",
    "audio": "assets/audio/0B6qg46ChnRO7OGhqSkRWcWFKd1k.mp3",
    "drive": "https://drive.google.com/file/d/0B6qg46ChnRO7OGhqSkRWcWFKd1k/view?usp=drivesdk&resourcekey=0-IexnN_zso6vtvdumLLk8Qw",
    "originalFilename": "1. Space-Time Continuum.mp3",
    "audioBytes": 12688275
  },
  {
    "id": "1ZwcQz0s2tg",
    "title": "First Love Twice",
    "artist": "Epic Cheesy Toast",
    "duration": "",
    "type": "Early archive",
    "youtube": "1ZwcQz0s2tg",
    "audio": "assets/audio/0B6qg46ChnRO7XzlCbFdPTVQ4VzQ.mp3",
    "drive": "https://drive.google.com/file/d/0B6qg46ChnRO7XzlCbFdPTVQ4VzQ/view?usp=drivesdk&resourcekey=0-7a9usBcIA_0Iko4NEffyEA",
    "originalFilename": "2. First Love Twice.mp3",
    "audioBytes": 13769725
  },
  {
    "id": "drive-15P2bALLS297Ty5zmxQ-RscwPZcCvRK4r",
    "title": "lord of power 2",
    "artist": "Unassigned",
    "type": "Studio archive · credit to confirm",
    "duration": "",
    "audio": "assets/audio/15P2bALLS297Ty5zmxQ-RscwPZcCvRK4r.mp3",
    "drive": "https://drive.google.com/file/d/15P2bALLS297Ty5zmxQ-RscwPZcCvRK4r/view?usp=drivesdk",
    "originalFilename": "lord of power_2.mp3",
    "audioBytes": 1222586
  },
  {
    "id": "drive-1OoBD5bR9l5-x2llyNMZ7uTfFQjWVjFQW",
    "title": "butterfly fever dream",
    "artist": "Unassigned",
    "type": "Studio archive · credit to confirm",
    "duration": "",
    "audio": "assets/audio/1OoBD5bR9l5-x2llyNMZ7uTfFQjWVjFQW.mp3",
    "drive": "https://drive.google.com/file/d/1OoBD5bR9l5-x2llyNMZ7uTfFQjWVjFQW/view?usp=drivesdk",
    "originalFilename": "butterfly fever dream.mp3",
    "audioBytes": 4222488
  },
  {
    "id": "drive-1faWYK58pOnWbULvQEG_48ZMXUvi8WMpr",
    "title": "Drum N Bass 03 final",
    "artist": "Unassigned",
    "type": "Studio archive · credit to confirm",
    "duration": "",
    "audio": "assets/audio/1faWYK58pOnWbULvQEG_48ZMXUvi8WMpr.mp3",
    "drive": "https://drive.google.com/file/d/1faWYK58pOnWbULvQEG_48ZMXUvi8WMpr/view?usp=drivesdk",
    "originalFilename": "Drum N Bass 03_final.mp3",
    "audioBytes": 9346682
  },
  {
    "id": "drive-1A_eNHvinSMvKYUWH1WosPNZPlT9ypOWQ",
    "title": "Мамбетский Мидтехно 08",
    "artist": "Unassigned",
    "type": "Studio archive · credit to confirm",
    "duration": "",
    "audio": "assets/audio/1A_eNHvinSMvKYUWH1WosPNZPlT9ypOWQ.mp3",
    "drive": "https://drive.google.com/file/d/1A_eNHvinSMvKYUWH1WosPNZPlT9ypOWQ/view?usp=drivesdk",
    "originalFilename": "Мамбетский Мидтехно 08.mp3",
    "audioBytes": 7825310
  },
  {
    "id": "drive-1qGjOPDqB3Wf224F9IU_B2StYnIkogYMM",
    "title": "WYCBA",
    "artist": "Fetch Quest",
    "type": "Drive original",
    "duration": "",
    "audio": "assets/audio/1qGjOPDqB3Wf224F9IU_B2StYnIkogYMM.mp3",
    "drive": "https://drive.google.com/file/d/1qGjOPDqB3Wf224F9IU_B2StYnIkogYMM/view?usp=drivesdk",
    "originalFilename": "Fetch Quest - WYCBA.mp3",
    "audioBytes": 7357196
  },
  {
    "id": "drive-1rIn_zRT1H1dT9oI2DGNjINC90cq0f38E",
    "title": "SYNTHWAVE FINAL",
    "artist": "Unassigned",
    "type": "Studio archive · credit to confirm",
    "duration": "",
    "audio": "assets/audio/1rIn_zRT1H1dT9oI2DGNjINC90cq0f38E.mp3",
    "drive": "https://drive.google.com/file/d/1rIn_zRT1H1dT9oI2DGNjINC90cq0f38E/view?usp=drivesdk",
    "originalFilename": "SYNTHWAVE FINAL.mp3",
    "audioBytes": 9857637
  },
  {
    "id": "drive-0B6qg46ChnRO7MjBra1pOeVVjNDg",
    "title": "Sometimes Evolution Sucks",
    "artist": "Unassigned",
    "type": "Studio archive · credit to confirm",
    "duration": "",
    "audio": "assets/audio/0B6qg46ChnRO7MjBra1pOeVVjNDg.mp3",
    "drive": "https://drive.google.com/file/d/0B6qg46ChnRO7MjBra1pOeVVjNDg/view?usp=drivesdk&resourcekey=0-5ns2yGpwkdGzEsHu2MGChg",
    "originalFilename": "Epic_Cheesy_Toast_-_Sometimes_Evolution_Sucks.mp3",
    "audioBytes": 12860674
  },
  {
    "id": "drive-0B6qg46ChnRO7MkQyczU2TUVWUjg",
    "title": "Mighty Maggots",
    "artist": "Epic Cheesy Toast",
    "type": "Drive original",
    "duration": "",
    "audio": "assets/audio/0B6qg46ChnRO7MkQyczU2TUVWUjg.mp3",
    "drive": "https://drive.google.com/file/d/0B6qg46ChnRO7MkQyczU2TUVWUjg/view?usp=drivesdk&resourcekey=0-RKDjXsGDwSW0Ceq6C4fyGA",
    "originalFilename": "Epic Cheesy Toast - Mighty Maggots.mp3",
    "audioBytes": 13095777
  },
  {
    "id": "drive-0B6qg46ChnRO7aV9Ha3doNDNCNUU",
    "title": "ASIANS!",
    "artist": "Epic Cheesy Toast",
    "type": "Drive original",
    "duration": "",
    "audio": "assets/audio/0B6qg46ChnRO7aV9Ha3doNDNCNUU.mp3",
    "drive": "https://drive.google.com/file/d/0B6qg46ChnRO7aV9Ha3doNDNCNUU/view?usp=drivesdk&resourcekey=0-1v4SU43eo97NC8S_LeA_5A",
    "originalFilename": "Epic Cheesy Toast - ASIANS!.mp3",
    "audioBytes": 12319418
  },
  {
    "id": "drive-0B6qg46ChnRO7YWVJeWpOWnpFMkE",
    "title": "Kleptomaniac",
    "artist": "Epic Cheesy Toast",
    "type": "Drive original",
    "duration": "",
    "audio": "assets/audio/0B6qg46ChnRO7YWVJeWpOWnpFMkE.mp3",
    "drive": "https://drive.google.com/file/d/0B6qg46ChnRO7YWVJeWpOWnpFMkE/view?usp=drivesdk&resourcekey=0-Vx4TrPXvmXsY_gWmYpqzUg",
    "originalFilename": "Epic Cheesy Toast - Kleptomaniac.mp3",
    "audioBytes": 9757371
  },
  {
    "id": "drive-0B6qg46ChnRO7b0lIcUpyeC1DNGM",
    "title": "Torque",
    "artist": "Epic Cheesy Toast",
    "type": "Drive original",
    "duration": "",
    "audio": "assets/audio/0B6qg46ChnRO7b0lIcUpyeC1DNGM.mp3",
    "drive": "https://drive.google.com/file/d/0B6qg46ChnRO7b0lIcUpyeC1DNGM/view?usp=drivesdk&resourcekey=0-g-JE-t6YqonQhmrin0F1Kw",
    "originalFilename": "Epic Cheesy Toast - Torque.mp3",
    "audioBytes": 10056320
  },
  {
    "id": "drive-0B6qg46ChnRO7b3pYNzNkcVhCaFU",
    "title": "Chinese Mafia",
    "artist": "Epic Cheesy Toast",
    "type": "Drive original",
    "duration": "",
    "audio": "assets/audio/0B6qg46ChnRO7b3pYNzNkcVhCaFU.mp3",
    "drive": "https://drive.google.com/file/d/0B6qg46ChnRO7b3pYNzNkcVhCaFU/view?usp=drivesdk&resourcekey=0-EVLhW9tcekjaKVFpn2J2yQ",
    "originalFilename": "Epic Cheesy Toast - Chinese Mafia.mp3",
    "audioBytes": 6105410
  },
  {
    "id": "drive-0B6qg46ChnRO7ajRlMjFkRkZkZlE",
    "title": "The Unleashed",
    "artist": "Epic Cheesy Toast",
    "type": "Drive original",
    "duration": "",
    "audio": "assets/audio/0B6qg46ChnRO7ajRlMjFkRkZkZlE.mp3",
    "drive": "https://drive.google.com/file/d/0B6qg46ChnRO7ajRlMjFkRkZkZlE/view?usp=drivesdk&resourcekey=0-xry6vkcGNB-YL5wbCv8XuA",
    "originalFilename": "Epic Cheese Toast - The Unleashed.mp3",
    "audioBytes": 5377625
  },
  {
    "id": "drive-0B6qg46ChnRO7WkVJakVqZkZ6dGc",
    "title": "Coming Home",
    "artist": "Epic Cheesy Toast",
    "type": "Drive original",
    "duration": "",
    "audio": "assets/audio/0B6qg46ChnRO7WkVJakVqZkZ6dGc.mp3",
    "drive": "https://drive.google.com/file/d/0B6qg46ChnRO7WkVJakVqZkZ6dGc/view?usp=drivesdk&resourcekey=0-OsJtGsRJJHU6HEecg2RmLA",
    "originalFilename": "12. Coming Home.mp3",
    "audioBytes": 10795049
  },
  {
    "id": "drive-0B6qg46ChnRO7R3JqYzhsV3luZVE",
    "title": "I'm Fine With That",
    "artist": "Epic Cheesy Toast",
    "type": "Drive original",
    "duration": "",
    "audio": "assets/audio/0B6qg46ChnRO7R3JqYzhsV3luZVE.mp3",
    "drive": "https://drive.google.com/file/d/0B6qg46ChnRO7R3JqYzhsV3luZVE/view?usp=drivesdk&resourcekey=0-vJmPclxHUtEQS1Pj7LaGHg",
    "originalFilename": "11. I'm Fine With That.mp3",
    "audioBytes": 13797903
  },
  {
    "id": "drive-0B6qg46ChnRO7Uy1fTURrX0ZJOEk",
    "title": "Hello America!",
    "artist": "Epic Cheesy Toast",
    "type": "Drive original",
    "duration": "",
    "audio": "assets/audio/0B6qg46ChnRO7Uy1fTURrX0ZJOEk.mp3",
    "drive": "https://drive.google.com/file/d/0B6qg46ChnRO7Uy1fTURrX0ZJOEk/view?usp=drivesdk&resourcekey=0-goABhDM086CzLZW4YYJ6pw",
    "originalFilename": "10. Hello America!.mp3",
    "audioBytes": 13398724
  },
  {
    "id": "drive-0B6qg46ChnRO7RUZMek5mZjhrWkE",
    "title": "Lunar",
    "artist": "Epic Cheesy Toast",
    "type": "Drive original",
    "duration": "",
    "audio": "assets/audio/0B6qg46ChnRO7RUZMek5mZjhrWkE.mp3",
    "drive": "https://drive.google.com/file/d/0B6qg46ChnRO7RUZMek5mZjhrWkE/view?usp=drivesdk&resourcekey=0-zY9i3OgRZUQEZoloO_KNHg",
    "originalFilename": "9. Lunar.mp3",
    "audioBytes": 13931561
  },
  {
    "id": "drive-0B6qg46ChnRO7b1Rud1dWaThaM1k",
    "title": "Art Of War",
    "artist": "Epic Cheesy Toast",
    "type": "Drive original",
    "duration": "",
    "audio": "assets/audio/0B6qg46ChnRO7b1Rud1dWaThaM1k.mp3",
    "drive": "https://drive.google.com/file/d/0B6qg46ChnRO7b1Rud1dWaThaM1k/view?usp=drivesdk&resourcekey=0-to-LQpp8OIg2aXfToHc5sg",
    "originalFilename": "8. Art Of War.mp3",
    "audioBytes": 13532628
  },
  {
    "id": "drive-0B6qg46ChnRO7RE9qeV9JOFNRVEE",
    "title": "Grandma's Isotopes",
    "artist": "Epic Cheesy Toast",
    "type": "Drive original",
    "duration": "",
    "audio": "assets/audio/0B6qg46ChnRO7RE9qeV9JOFNRVEE.mp3",
    "drive": "https://drive.google.com/file/d/0B6qg46ChnRO7RE9qeV9JOFNRVEE/view?usp=drivesdk&resourcekey=0-JuhoKb_apJWb8AvsTdtx-g",
    "originalFilename": "7. Grandma's Isotopes.mp3",
    "audioBytes": 11864879
  },
  {
    "id": "drive-0B6qg46ChnRO7bWpndnlaeWFoSzA",
    "title": "Caffeine Addicted",
    "artist": "Epic Cheesy Toast",
    "type": "Drive original",
    "duration": "",
    "audio": "assets/audio/0B6qg46ChnRO7bWpndnlaeWFoSzA.mp3",
    "drive": "https://drive.google.com/file/d/0B6qg46ChnRO7bWpndnlaeWFoSzA/view?usp=drivesdk&resourcekey=0-K82mmh0xojbAzZLkn257Ew",
    "originalFilename": "6. Caffeine Addicted.mp3",
    "audioBytes": 12570293
  },
  {
    "id": "drive-0B6qg46ChnRO7RUVKcTJ0RXU1RWM",
    "title": "Bassey Trebleson",
    "artist": "Epic Cheesy Toast",
    "type": "Drive original",
    "duration": "",
    "audio": "assets/audio/0B6qg46ChnRO7RUVKcTJ0RXU1RWM.mp3",
    "drive": "https://drive.google.com/file/d/0B6qg46ChnRO7RUVKcTJ0RXU1RWM/view?usp=drivesdk&resourcekey=0-jGy9_3Twp6JRghRFWODkcA",
    "originalFilename": "5. Bassey Trebleson.mp3",
    "audioBytes": 12507631
  },
  {
    "id": "drive-0B6qg46ChnRO7WXFnSElYRlNYN1k",
    "title": "Humanoids",
    "artist": "Epic Cheesy Toast",
    "type": "Drive original",
    "duration": "",
    "audio": "assets/audio/0B6qg46ChnRO7WXFnSElYRlNYN1k.mp3",
    "drive": "https://drive.google.com/file/d/0B6qg46ChnRO7WXFnSElYRlNYN1k/view?usp=drivesdk&resourcekey=0--nvM-14-GhFa9o_D98NhPg",
    "originalFilename": "4. Humanoids.mp3",
    "audioBytes": 9474147
  },
  {
    "id": "drive-0B6qg46ChnRO7V0tNUlJ5aTRHazA",
    "title": "Reminiscence",
    "artist": "Epic Cheesy Toast",
    "type": "Drive original",
    "duration": "",
    "audio": "assets/audio/0B6qg46ChnRO7V0tNUlJ5aTRHazA.mp3",
    "drive": "https://drive.google.com/file/d/0B6qg46ChnRO7V0tNUlJ5aTRHazA/view?usp=drivesdk&resourcekey=0-5UTTQGrVVy49LX5r7yuvSQ",
    "originalFilename": "3. Reminiscence.mp3",
    "audioBytes": 15669275
  },
  {
    "id": "drive-1JiVTD6zoYjeujaAZ6KtC1eLrGmeZ84f-",
    "title": "Say No More",
    "artist": "Audionerds",
    "type": "Drive original",
    "duration": "",
    "audio": "assets/audio/1JiVTD6zoYjeujaAZ6KtC1eLrGmeZ84f-.mp3",
    "drive": "https://drive.google.com/file/d/1JiVTD6zoYjeujaAZ6KtC1eLrGmeZ84f-/view?usp=drivesdk",
    "originalFilename": "Audionerds - Say No More (Original Mix).mp3",
    "audioBytes": 10600559
  },
  {
    "id": "drive-1MZq8yde9SGTceGrj81AsoaSDubp1j7tc",
    "title": "Hitchhike",
    "artist": "Audionerds",
    "type": "Drive original",
    "duration": "",
    "audio": "assets/audio/1MZq8yde9SGTceGrj81AsoaSDubp1j7tc.mp3",
    "drive": "https://drive.google.com/file/d/1MZq8yde9SGTceGrj81AsoaSDubp1j7tc/view?usp=drivesdk",
    "originalFilename": "Audionerds - Hitchhike (Original Mix).mp3",
    "audioBytes": 9752102
  },
  {
    "id": "drive-15VBuSTsUeZtW9am90hMDDp53plVVV5iE",
    "title": "Mutation",
    "artist": "Unassigned",
    "type": "Studio archive · credit to confirm",
    "duration": "",
    "audio": "assets/audio/15VBuSTsUeZtW9am90hMDDp53plVVV5iE.mp3",
    "drive": "https://drive.google.com/file/d/15VBuSTsUeZtW9am90hMDDp53plVVV5iE/view?usp=drivesdk",
    "originalFilename": "Mutation_Mastered.mp3",
    "audioBytes": 9227567,
    "audioNote": "320 kbps listening copy made from the WAV master. The unmodified WAV is preserved in the original masters backup."
  },
  {
    "id": "drive-0B6qg46ChnRO7MW92eUxzLW1yVjg",
    "title": "DanchikBaha [minus wave]",
    "artist": "Unassigned",
    "type": "Studio archive · credit to confirm",
    "duration": "",
    "audio": "assets/audio/0B6qg46ChnRO7MW92eUxzLW1yVjg.mp3",
    "drive": "https://drive.google.com/file/d/0B6qg46ChnRO7MW92eUxzLW1yVjg/view?usp=drivesdk&resourcekey=0-EiGW4HMnNhsS5P2MqMxtUw",
    "originalFilename": "DanchikBaha [minus wave].mp3",
    "audioBytes": 4792991,
    "audioNote": "320 kbps listening copy made from the WAV master. The unmodified WAV is preserved in the original masters backup."
  },
  {
    "id": "drive-1yATBQ2IaHV05AuTaA7_w3W5yPIFo_uNa",
    "title": "AP mastered",
    "artist": "Unassigned",
    "type": "Studio archive · credit to confirm",
    "duration": "",
    "audio": "assets/audio/1yATBQ2IaHV05AuTaA7_w3W5yPIFo_uNa.mp3",
    "drive": "https://drive.google.com/file/d/1yATBQ2IaHV05AuTaA7_w3W5yPIFo_uNa/view?usp=drivesdk",
    "originalFilename": "AP mastered.mp3",
    "audioBytes": 12641219,
    "audioNote": "320 kbps listening copy made from the WAV master. The unmodified WAV is preserved in the original masters backup."
  },
  {
    "id": "drive-13eas8jXbRojM-rvWChDiEa1wq4IMOVk0",
    "title": "Decoy",
    "artist": "Unassigned",
    "type": "Studio archive · credit to confirm",
    "duration": "",
    "audio": "assets/audio/13eas8jXbRojM-rvWChDiEa1wq4IMOVk0.mp3",
    "drive": "https://drive.google.com/file/d/13eas8jXbRojM-rvWChDiEa1wq4IMOVk0/view?usp=drivesdk",
    "originalFilename": "Decoy mastered.mp3",
    "audioBytes": 10058231,
    "audioNote": "320 kbps listening copy made from the WAV master. The unmodified WAV is preserved in the original masters backup."
  },
  {
    "id": "drive-1EcHk60ZVhAA2G8q_Gw_ti-8TdKnSeh9b",
    "title": "Crossover",
    "artist": "Audionerds",
    "type": "Earlier master",
    "duration": "",
    "audio": "assets/audio/1EcHk60ZVhAA2G8q_Gw_ti-8TdKnSeh9b.mp3",
    "drive": "https://drive.google.com/file/d/1EcHk60ZVhAA2G8q_Gw_ti-8TdKnSeh9b/view?usp=drivesdk",
    "originalFilename": "Audionerds - Crossover.mp3",
    "audioBytes": 12321480,
    "audioNote": "320 kbps listening copy made from the WAV master. The unmodified WAV is preserved in the original masters backup."
  }
];
