let currentTrack=catalog.find(t=>t.id==='oasfLfWYgTo'),youtubePlayer=null,youtubeReady=false,requestedPlayback=false,playerMode='youtube';
const playerScreen=document.querySelector('.player-screen'),playerStatus=document.getElementById('player-status'),modeButtons={audio:document.getElementById('audio-mode'),youtube:document.getElementById('youtube-mode'),spotify:document.getElementById('spotify-mode'),soundcloud:document.getElementById('soundcloud-mode')};
function updateTrackDetails(){document.getElementById('playing-title').textContent=currentTrack.title;document.getElementById('playing-artist').textContent=currentTrack.credit||currentTrack.artist;const original=document.getElementById('original-track');const url=playerMode==='audio'?currentTrack.drive||currentTrack.soundcloud:playerMode==='spotify'?`https://open.spotify.com/${currentTrack.spotifyKind==='album'?'album':'track'}/${currentTrack.spotify}`:playerMode==='soundcloud'?currentTrack.soundcloud:`https://music.youtube.com/watch?v=${currentTrack.youtube}`;original.hidden=!url;if(url)original.href=url;for(const[mode,b]of Object.entries(modeButtons)){b.hidden=!currentTrack[mode];b.classList.toggle('active',mode===playerMode);b.setAttribute('aria-pressed',String(mode===playerMode));}document.querySelectorAll('[data-track]').forEach(row=>row.classList.toggle('selected-track',row.dataset.track===currentTrack.id));document.querySelectorAll('[data-release]').forEach(row=>row.classList.toggle('selected-track',window.releaseGroups.find(group=>group.id===row.dataset.release)?.tracks.includes(currentTrack.id))); }
function mountYoutubeFrame(){
 const frame=document.createElement('iframe');frame.id='youtube-player';frame.title=currentTrack.title+' — YouTube player';frame.referrerPolicy='strict-origin-when-cross-origin';frame.allow='autoplay; encrypted-media; picture-in-picture; fullscreen';frame.allowFullscreen=true;
 const params=new URLSearchParams({autoplay:requestedPlayback?'1':'0',enablejsapi:'1',playsinline:'1',controls:'1',rel:'0',origin:location.origin});
 frame.src='https://www.youtube.com/embed/'+encodeURIComponent(currentTrack.youtube)+'?'+params;
 playerScreen.replaceChildren(frame);playerScreen.dataset.mode='youtube';
}
function createYoutubePlayer(){
 if(!window.YT?.Player||playerMode!=='youtube'||youtubePlayer)return;
 const videoId=currentTrack.youtube;
 const active=e=>playerMode==='youtube'&&currentTrack.youtube===videoId&&e.target.getIframe()===document.getElementById('youtube-player');
 youtubePlayer=new YT.Player('youtube-player',{events:{
  onReady:e=>{if(!active(e))return;youtubeReady=true;playerStatus.textContent='Ready. Press play to listen.';if(requestedPlayback)e.target.playVideo();window.syncPlayerTransport?.();},
  onStateChange:e=>{if(!active(e))return;if(e.data===1){requestedPlayback=false;playerStatus.textContent='Playing on YouTube.';}else if(e.data===2)playerStatus.textContent='Paused.';else if(e.data===0){playerStatus.textContent='Track finished.';window.handleTrackEnded?.();}else if(e.data===3)playerStatus.textContent='Buffering…';window.syncPlayerTransport?.();},
  onError:e=>{if(!active(e))return;requestedPlayback=false;const errors={2:'This YouTube link is invalid.',100:'This video is unavailable on YouTube.',101:'This upload does not allow embedded playback.',150:'This upload does not allow embedded playback.',153:'YouTube could not verify this browser preview.'};playerStatus.textContent=(errors[e.data]||'YouTube could not play this upload here.')+' Choose another source or open the original.';window.syncPlayerTransport?.();},
  onAutoplayBlocked:e=>{if(!active(e))return;requestedPlayback=false;playerStatus.textContent='Press play inside the YouTube player to start.';window.syncPlayerTransport?.();}
 }});
}
window.onYouTubeIframeAPIReady=createYoutubePlayer;
function showPlayer(mode,play=false){playerScreen.querySelector('audio')?.pause();youtubePlayer?.destroy();youtubePlayer=null;youtubeReady=false;requestedPlayback=play;playerMode=mode;window.soundcloudWidget=null;playerScreen.dataset.mode=mode;playerScreen.classList.toggle('spotify-player',mode==='spotify');
 if(mode==='audio'){playerScreen.innerHTML=`<div class="archive-audio-player"><img src="${artwork[currentTrack.id].artwork}" alt="${escapeHTML(artwork[currentTrack.id].missing?'Cover not on file':'Artwork for '+currentTrack.title)}"><audio crossorigin="anonymous" controls preload="metadata" src="${currentTrack.audio}"></audio><p>${currentTrack.audioNote?'ARCHIVE LISTENING COPY':'ORIGINAL ARCHIVE COPY'}<br>${escapeHTML(currentTrack.originalFilename||currentTrack.title)}</p><a href="${currentTrack.audio}" download="${escapeHTML(currentTrack.originalFilename||currentTrack.title+'.mp3')}">DOWNLOAD AUDIO</a></div>`;const element=playerScreen.querySelector('audio');const audioIsActive=()=>playerMode==='audio'&&playerScreen.querySelector('audio')===element;element.addEventListener('play',()=>{if(audioIsActive())playerStatus.textContent='Playing the saved archive copy.';});element.addEventListener('pause',()=>{if(audioIsActive())playerStatus.textContent='Paused.';});element.addEventListener('ended',()=>{if(!audioIsActive())return;playerStatus.textContent='Track finished.';window.handleTrackEnded?.();});element.addEventListener('error',()=>{if(audioIsActive())playerStatus.textContent='The archive file could not load. Try another source.';});playerStatus.textContent='Saved with this site. Press play to listen.';if(play)element.play().catch(()=>{if(audioIsActive())playerStatus.textContent='Press play in the audio player to start.';});}
 else if(mode==='youtube'){mountYoutubeFrame();createYoutubePlayer();playerStatus.textContent=play?'Loading the track…':'Press play to listen here.';}
 else if(mode==='spotify'){playerScreen.innerHTML=`<iframe src="https://open.spotify.com/embed/${currentTrack.spotifyKind==='album'?'album':'track'}/${currentTrack.spotify}" title="${escapeHTML(currentTrack.title)} — Spotify player" width="100%" height="152" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" style="border:0;border-radius:12px"></iframe>`;playerStatus.textContent='Press play in the Spotify player.';}
 else {playerScreen.innerHTML=`<iframe title="${escapeHTML(currentTrack.title)} — SoundCloud player" width="100%" height="300" style="border:0" allow="autoplay" src="https://w.soundcloud.com/player/?url=${encodeURIComponent(currentTrack.soundcloud)}&auto_play=${play}&hide_related=true&show_comments=false&show_reposts=false&visual=false&color=bcff35"></iframe>`;playerStatus.textContent='Playback supplied by SoundCloud.';connectSoundCloud(play);}updateTrackDetails();window.dispatchEvent(new Event("trackchange"));}
function playTrack(id,source){const t=catalog.find(t=>t.id===id);if(!t)return;currentTrack=t;showPlayer(source&&t[source]?source:t.audio?'audio':t.youtube?'youtube':t.soundcloud?'soundcloud':'spotify',true);window.floatMusicPlayer?.();}
document.addEventListener('click',event=>{const button=event.target.closest('[data-play]');if(button){event.preventDefault();playTrack(button.dataset.play,button.dataset.source);}});for(const[mode,b]of Object.entries(modeButtons))b.addEventListener('click',()=>{if(currentTrack[mode])showPlayer(mode,true);});mountYoutubeFrame();updateTrackDetails();if(window.YT?.Player)createYoutubePlayer();const api=document.createElement('script');api.src='https://www.youtube.com/iframe_api';api.async=true;api.addEventListener('error',()=>{if(playerMode==='youtube')playerStatus.textContent='The player could not load. Open the original to listen.';});document.head.appendChild(api);


function connectSoundCloud(play=false){
 if(playerMode!=='soundcloud'||!window.SC?.Widget)return;
 const frame=playerScreen.querySelector('iframe'),widget=SC.Widget(frame);window.soundcloudWidget=widget;
 const active=()=>window.soundcloudWidget===widget&&playerMode==='soundcloud';
 widget.bind(SC.Widget.Events.READY,()=>{if(!active())return;playerStatus.textContent='SoundCloud ready.';if(play)widget.play();window.syncPlayerTransport?.();});widget.bind(SC.Widget.Events.ERROR,()=>{if(active())playerStatus.textContent='SoundCloud could not load this upload. Choose another source or open the original.';});
 widget.bind(SC.Widget.Events.PLAY,()=>{if(active()){playerStatus.textContent='Playing on SoundCloud.';window.syncPlayerTransport?.();}});
 widget.bind(SC.Widget.Events.PAUSE,()=>{if(active()){playerStatus.textContent='Paused.';window.syncPlayerTransport?.();}});
 widget.bind(SC.Widget.Events.FINISH,()=>{if(active())window.handleTrackEnded?.();});
}
const soundcloudAPI=document.createElement('script');soundcloudAPI.src='https://w.soundcloud.com/player/api.js';soundcloudAPI.async=true;soundcloudAPI.onload=()=>connectSoundCloud(requestedPlayback);document.head.appendChild(soundcloudAPI);
