import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const read=async name=>JSON.parse(await fs.readFile(path.join(root,name),'utf8'));
const config=await read('release-settings.json'),catalog=await read('catalog.json'),previous=await read('latest-release.json');
const coverData=JSON.parse((await fs.readFile(path.join(root,'artwork.js'),'utf8')).split('=').slice(1).join('=').trim().replace(/;\s*$/,''));
const text=async url=>{const r=await fetch(url,{headers:{'Accept-Language':'en-US,en;q=0.9'},signal:AbortSignal.timeout(25000)});if(!r.ok)throw Error(`${r.status} ${url}`);return r.text();};
const decode=s=>s.replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&apos;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>');
const walk=(v,fn)=>{if(!v||typeof v!=='object')return;fn(v);for(const child of Object.values(v))if(typeof child==='object')walk(child,fn);};
const candidates=[],checks=[];
function eligible(track){if(config.excludedIds.includes(track.id))return false;if(config.includeEdits)return true;return !/remix|recolor|rework|slowed|sped up|reverb|mashup|instrumental.*remix|but it.s/i.test(track.title)&&!['Remix / edit','Remix','Reupload'].includes(track.type);}
async function youtube(channel){const page=await text(`https://www.youtube.com/channel/${channel.id}/videos`);const data=JSON.parse(page.match(/var ytInitialData = (.*?);<\/script>/s)?.[1]||'null');if(!data)throw Error('YouTube channel data missing');const videos=[];walk(data,x=>{const model=x.lockupViewModel;if(model?.contentId&&model.contentType==='LOCKUP_CONTENT_TYPE_VIDEO')videos.push({id:model.contentId,title:model.metadata?.lockupMetadataViewModel?.title?.content||''});if(x.videoRenderer)videos.push({id:x.videoRenderer.videoId,title:x.videoRenderer.title?.runs?.map(r=>r.text).join('')||''});});if(!videos.length)throw Error('No channel videos found');for(const video of videos.slice(0,8)){const known=catalog.find(t=>t.youtube===video.id);const track={...known,id:video.id,title:known?.title||video.title.replace(new RegExp('^'+channel.artist+'\\s*[-–:]\\s*','i'),''),artist:known?.artist||channel.artist,youtube:video.id,type:known?.type||'Release'};if(!eligible(track))continue;
 // Unknown uploads with a different named artist are never presented as our originals.
 if(!known&&!config.includeEdits&&/\s[-–]\s/.test(video.title)&&!video.title.toLowerCase().startsWith(channel.artist.toLowerCase()))continue;
 const watch=await text(`https://www.youtube.com/watch?v=${video.id}`);const raw=watch.match(/var ytInitialPlayerResponse = (.*?);(?:var |<\/script>)/s)?.[1];if(!raw)continue;const response=JSON.parse(raw),meta=response.microformat?.playerMicroformatRenderer;if(meta?.externalChannelId!==channel.id||!meta.publishDate)continue;
 track.releaseDate=meta.publishDate.slice(0,10);track.description=response.videoDetails?.shortDescription||'';track.sourceUrl=`https://www.youtube.com/watch?v=${video.id}`;track.remoteArtwork=response.videoDetails?.thumbnail?.thumbnails?.at(-1)?.url;track.genre=(track.description.match(/(?:^|\n)genre\s*:\s*([^\n]+)/i)||[])[1]||null;candidates.push(track);
}return `${channel.artist}: ${videos.length} uploads checked`;}
async function soundcloud(){const page=await text('https://soundcloud.com/fetchquest');let count=0;for(const match of page.matchAll(/<article\b[^>]*>(.*?)<\/article>/gs)){const block=match[1],song=block.match(/<a itemprop="url" href="([^"]+)">([^<]+)<\/a>/),date=block.match(/<time[^>]*>([^<]+)<\/time>/);if(!song||!date)continue;count++;const url=new URL(decode(song[1]),'https://soundcloud.com').href,known=catalog.find(t=>t.soundcloud===url);const track={...known,id:known?.id||`sc-${song[1].split('/').at(-1)}`,title:known?.title||decode(song[2]),artist:'Fetch Quest',soundcloud:url,type:known?.type||'Release',releaseDate:date[1].slice(0,10),genre:decode(block.match(/itemprop="genre" content="([^"]+)"/)?.[1]||''),sourceUrl:url};if(eligible(track))candidates.push(track);}if(!count)throw Error('SoundCloud track metadata missing');return `${count} SoundCloud uploads checked`;}
async function spotify(){const page=await text('https://open.spotify.com/artist/2AsQITCEKRoMrBVx1sqJtX');const albums=[...new Set([...page.matchAll(/href="\/album\/([A-Za-z0-9]+)"/g)].map(x=>x[1]))].slice(0,12);let matched=0;for(const id of albums){const album=await text(`https://open.spotify.com/album/${id}`);const schemas=[...album.matchAll(/<script[^>]*type="application\/ld\+json"[^>]*>(.*?)<\/script>/gs)].map(x=>{try{return JSON.parse(x[1]);}catch{return null;}});for(const schema of schemas){if(!schema)continue;const items=[];walk(schema,x=>{if(x['@type']==='MusicRecording'||x['@type']==='MusicAlbum')items.push(x);});for(const item of items){if(config.excludedTitles.some(t=>t.toLowerCase()===String(item.name||'').toLowerCase()))continue;const known=catalog.find(t=>t.title.toLowerCase()===String(item.name||'').toLowerCase()&&t.artist==='Fetch Quest');const date=item.datePublished||schema.datePublished;if(!date)continue;
 // New Spotify albums must identify Fetch Quest in the release metadata and link
 // the exact artist profile the owner supplied, not merely a search result.
 const verifiedArtist=String(item.description||'').includes('· Fetch Quest ·')&&album.includes('/artist/2AsQITCEKRoMrBVx1sqJtX');if(!known&&!verifiedArtist)continue;matched++;
 const track=known||{id:`spotify-album-${id}`,title:item.name,artist:'Fetch Quest',type:'Release',spotify:id,spotifyKind:'album',description:'',remoteArtwork:decode(album.match(/<meta[^>]*property="og:image"[^>]*content="([^"]+)"/)?.[1]||''),duration:''};if(eligible(track))candidates.push({...track,releaseDate:date.slice(0,10),sourceUrl:`https://open.spotify.com/album/${id}`});}}}return `Spotify: ${albums.length} releases checked, ${matched} verified releases (excluded titles skipped)`;}
for(const [name,task] of [['YouTube peacepipe04',()=>youtube(config.youtubeChannels[0])],['YouTube Music Fetch Quest',()=>youtube(config.youtubeChannels[1])],['SoundCloud',soundcloud],['Spotify',spotify]]){try{checks.push({source:name,ok:true,detail:await task()});}catch(error){checks.push({source:name,ok:false,detail:error.message});console.warn(name,error.message);}}
const best=candidates.filter(t=>Date.parse(t.releaseDate)<=Date.now()).sort((a,b)=>b.releaseDate.localeCompare(a.releaseDate))[0];
const report={checkedAt:new Date().toISOString(),sources:checks,candidateCount:candidates.length};console.log(JSON.stringify(report,null,2));await fs.writeFile(path.join(root,'release-sync-status.json'),JSON.stringify(report,null,2)+'\n');
if(!best){throw Error('No verified releases found; keeping the last successful release.');}
if(best.releaseDate<previous.releaseDate||best.id===previous.id){console.log(`Keeping ${previous.title}.`);process.exit(0);}
if(best.soundcloud&&!best.remoteArtwork){try{const embed=JSON.parse(await text('https://soundcloud.com/oembed?format=json&url='+encodeURIComponent(best.soundcloud)));best.remoteArtwork=embed.thumbnail_url;}catch(error){console.warn('SoundCloud artwork:',error.message);}}
let cover=coverData[best.id]?.artwork;
if(!cover&&best.remoteArtwork){const response=await fetch(best.remoteArtwork,{signal:AbortSignal.timeout(25000)});if(response.ok&&response.headers.get('content-type')?.startsWith('image/')){cover=`assets/artwork/latest-${best.id.replace(/[^\w-]/g,'')}.jpg`;await fs.writeFile(path.join(root,cover),Buffer.from(await response.arrayBuffer()));}}
const notes=config.notes[best.id]||{};
const releaseStatus=best.releaseStatus||(best.spotify?'official':(['peacepipe04','Epic Cheesy Toast'].includes(best.artist)?'unofficial':'unverified'));
const release={...best,releaseStatus,streamingLinks:best.streamingLinks||(best.spotify?{spotify:`https://open.spotify.com/${best.spotifyKind==='album'?'album':'track'}/${best.spotify}`} : {}),artwork:cover||'assets/chicken-balls-logo-purple.svg',description:notes.description||best.description?.split('\n').filter(Boolean).slice(0,2).join(' ').slice(0,650)||'The newest release from Chicken Balls. Press play to explore.',descriptionSource:notes.description?'Label release notes':'Artist’s release notes',genre:notes.genre||best.genre||null,feeling:notes.feeling||null,verifiedAt:report.checkedAt};
if(!catalog.some(t=>t.id===best.id)){catalog.unshift({...best,releaseStatus:release.releaseStatus,streamingLinks:release.streamingLinks,duration:best.duration||''});coverData[best.id]={title:best.title,artwork:release.artwork,provider:best.youtube?'YouTube':'SoundCloud'};await fs.writeFile(path.join(root,'catalog.json'),JSON.stringify(catalog,null,2)+'\n');await fs.writeFile(path.join(root,'catalog.js'),'const catalog = '+JSON.stringify(catalog,null,2)+';\n');await fs.writeFile(path.join(root,'artwork.js'),'const artwork = '+JSON.stringify(coverData,null,2)+';\n');}
await fs.writeFile(path.join(root,'latest-release.json'),JSON.stringify(release,null,2)+'\n');await fs.writeFile(path.join(root,'latest-release.js'),'window.latestRelease = '+JSON.stringify(release,null,2)+';\n');console.log(`Featured ${release.title}, ${release.releaseDate}.`);

